export const navigationItems = [
  { id: 'overview', label: 'Overview', kind: 'admin', endpoint: '/admin/dashboard/overview' },
  { id: 'users', label: 'Users', kind: 'admin', endpoint: '/admin/users' },
  { id: 'content', label: 'Content Moderation', kind: 'admin', endpoint: '/admin/content' },
  { id: 'reports', label: 'Reports', kind: 'admin', endpoint: '/admin/reports' },
  { id: 'support', label: 'Support', kind: 'admin', endpoint: '/admin/support-operations' },
  { id: 'marketplace', label: 'Marketplace', kind: 'admin', endpoint: '/admin/marketplace' },
  { id: 'jobs', label: 'Jobs', kind: 'admin', endpoint: '/admin/jobs' },
  { id: 'events', label: 'Events', kind: 'admin', endpoint: '/admin/events' },
  { id: 'communities', label: 'Communities', kind: 'admin', endpoint: '/admin/communities' },
  { id: 'pages', label: 'Pages', kind: 'admin', endpoint: '/admin/pages' },
  { id: 'liveStreams', label: 'Live Streams', kind: 'admin', endpoint: '/admin/live-streams' },
  { id: 'revenue', label: 'Revenue & Subs', kind: 'admin', endpoint: '/admin/dashboard/revenue' },
  { id: 'walletSubscriptions', label: 'Wallet & Subs', kind: 'admin', endpoint: '/admin/wallet-subscriptions' },
  { id: 'premiumPlans', label: 'Premium Plans', kind: 'admin', endpoint: '/admin/premium-plans' },
  { id: 'notifications', label: 'Notifications', kind: 'admin', endpoint: '/admin/broadcast-campaigns' },
  { id: 'notificationDevices', label: 'Notification Devices', kind: 'admin', endpoint: '/admin/notification-devices' },
  { id: 'adminSessions', label: 'Admin Sessions', kind: 'admin', endpoint: '/admin/auth/sessions' },
  { id: 'settings', label: 'Settings', kind: 'admin', endpoint: '/admin/settings' },
  { id: 'audit', label: 'Audit Logs', kind: 'admin', endpoint: '/admin/audit-logs' },
]
