export const navigationItems = [
  { id: 'overview', label: 'Overview', kind: 'admin', endpoint: '/admin/dashboard/overview' },
  { id: 'users', label: 'Users', kind: 'admin', endpoint: '/admin/users' },
  { id: 'content', label: 'Content Moderation', kind: 'admin', endpoint: '/admin/content' },
  { id: 'posts', label: 'Posts', kind: 'admin', endpoint: '/admin/posts' },
  { id: 'stories', label: 'Stories', kind: 'admin', endpoint: '/admin/stories' },
  { id: 'reels', label: 'Reels', kind: 'admin', endpoint: '/admin/reels' },
  { id: 'comments', label: 'Comments', kind: 'admin', endpoint: '/admin/comments' },
  { id: 'reports', label: 'Reports', kind: 'admin', endpoint: '/admin/reports' },
  { id: 'support', label: 'Support', kind: 'admin', endpoint: '/admin/support-operations' },
  { id: 'marketplace', label: 'Marketplace', kind: 'admin', endpoint: '/admin/marketplace' },
  { id: 'jobs', label: 'Jobs', kind: 'admin', endpoint: '/admin/jobs' },
  { id: 'events', label: 'Events', kind: 'admin', endpoint: '/admin/events' },
  { id: 'communities', label: 'Communities', kind: 'admin', endpoint: '/admin/communities' },
  { id: 'pages', label: 'Pages', kind: 'admin', endpoint: '/admin/pages' },
  { id: 'liveStreams', label: 'Live Streams', kind: 'admin', endpoint: '/admin/live-streams' },
  { id: 'revenue', label: 'Revenue & Subs', kind: 'admin', endpoint: '/admin/dashboard/revenue' },
  { id: 'wallet', label: 'Wallet', kind: 'admin', endpoint: '/admin/wallet' },
  { id: 'subscriptions', label: 'Subscriptions', kind: 'admin', endpoint: '/admin/subscriptions' },
  { id: 'walletSubscriptions', label: 'Wallet & Subs', kind: 'admin', endpoint: '/admin/wallet-subscriptions' },
  { id: 'premiumPlans', label: 'Premium Plans', kind: 'admin', endpoint: '/admin/premium-plans' },
  { id: 'analytics', label: 'Analytics', kind: 'admin', endpoint: '/admin/analytics-pipeline' },
  { id: 'rbac', label: 'RBAC', kind: 'admin', endpoint: '/admin/rbac' },
  { id: 'adminStaff', label: 'Admin Staff', kind: 'admin', endpoint: '/admin/staff' },
  { id: 'notifications', label: 'Notifications', kind: 'admin', endpoint: '/admin/notification-campaigns' },
  { id: 'notificationDevices', label: 'Notification Devices', kind: 'admin', endpoint: '/admin/notification-devices' },
  { id: 'adminSessions', label: 'Admin Sessions', kind: 'admin', endpoint: '/admin/auth/sessions' },
  { id: 'settings', label: 'Settings', kind: 'admin', endpoint: '/admin/settings' },
  { id: 'audit', label: 'Audit Logs', kind: 'admin', endpoint: '/admin/audit-logs' },
]

export const appSettingsSections = [
  { key: 'account-settings', label: 'Account Settings' },
  { key: 'password-security', label: 'Password & Security' },
  { key: 'devices-sessions', label: 'Devices & Sessions' },
  { key: 'archive-center', label: 'Archive Center' },
  { key: 'privacy', label: 'Privacy' },
  { key: 'advanced-privacy-controls', label: 'Advanced Privacy Controls' },
  { key: 'blocked-users', label: 'Blocked Users' },
  { key: 'help-safety', label: 'Help & Safety' },
  { key: 'notifications', label: 'Notifications' },
  { key: 'messages-calls', label: 'Messages & Calls' },
  { key: 'feed-content-preferences', label: 'Feed & Content Preferences' },
  { key: 'creator-professional-tools', label: 'Creator / Professional Tools' },
  { key: 'monetization-payments', label: 'Monetization & Payments' },
  { key: 'communities-groups', label: 'Communities & Groups' },
  { key: 'connected-apps', label: 'Connected Apps' },
  { key: 'language-accessibility', label: 'Language & Accessibility' },
  { key: 'language-region', label: 'Language & Region' },
  { key: 'accessibility', label: 'Accessibility' },
  { key: 'localization-support', label: 'Localization Support' },
  { key: 'data-privacy-center', label: 'Data & Privacy Center' },
  { key: 'about', label: 'About' },
]

export const webNavigationSections = [
  { key: 'home', label: 'Home', description: 'Main feed and composer route.' },
  { key: 'stories', label: 'Stories', description: 'Story rail on the web home feed.' },
  { key: 'reels', label: 'Reels', description: 'Short-form video web route.' },
  { key: 'explore', label: 'Explore', description: 'Search discovery and trends route.' },
  { key: 'marketplace', label: 'Marketplace', description: 'Products and seller discovery route.' },
  { key: 'jobs', label: 'Jobs', description: 'Jobs and hiring route.' },
  { key: 'events', label: 'Events', description: 'Events discovery and RSVP route.' },
  { key: 'communities', label: 'Communities', description: 'Communities list and membership route.' },
  { key: 'pages', label: 'Pages', description: 'Public pages directory route.' },
  { key: 'calls', label: 'Calls', description: 'Calls and RTC entry route.' },
  { key: 'live-streams', label: 'Live Streams', description: 'Live stream discovery route.' },
  { key: 'notifications', label: 'Notifications', description: 'Notification inbox route.' },
  { key: 'messages', label: 'Messages', description: 'Direct messaging route.' },
  { key: 'connections', label: 'Connections', description: 'Follower and connection management route.' },
  { key: 'bookmarks', label: 'Bookmarks', description: 'Saved post route.' },
  { key: 'saved-collections', label: 'Saved Collections', description: 'Saved collections workspace.' },
  { key: 'drafts', label: 'Drafts', description: 'Draft posts route.' },
  { key: 'scheduling', label: 'Scheduling', description: 'Scheduled publishing route.' },
  { key: 'upload-manager', label: 'Upload Manager', description: 'Media upload queue route.' },
  { key: 'groups', label: 'Groups', description: 'Groups route.' },
  { key: 'group-chat', label: 'Group Chat', description: 'Group chat route.' },
  { key: 'creator-tools', label: 'Creator Tools', description: 'Creator and professional tools route.' },
  { key: 'wallet', label: 'Wallet', description: 'Wallet and payments route.' },
  { key: 'premium', label: 'Premium', description: 'Premium membership route.' },
  { key: 'subscriptions', label: 'Subscriptions', description: 'Subscription management route.' },
  { key: 'support', label: 'Help & Support', description: 'Support and help route.' },
  { key: 'verification', label: 'Verification', description: 'Verification request route.' },
  { key: 'activity-sessions', label: 'Activity Sessions', description: 'Session history route.' },
  { key: 'account-switching', label: 'Account Switching', description: 'Linked account switching route.' },
  { key: 'blocked-users', label: 'Blocked Users', description: 'Blocked accounts route.' },
  { key: 'invite-referral', label: 'Invite Referral', description: 'Referral route.' },
  { key: 'archive', label: 'Archive Center', description: 'Archived posts, stories, and reels route.' },
  { key: 'profile', label: 'Profile', description: 'Profile route.' },
  { key: 'settings', label: 'Settings', description: 'User settings route.' },
]

export const postAdminControls = [
  { key: 'admin.controls.posts.visible', label: 'Show Posts Section', description: 'Keeps the dedicated posts module visible in the admin drawer.' },
  { key: 'admin.controls.posts.create', label: 'Create Posts', description: 'Lets admins publish posts from admin-managed app flows.' },
  { key: 'admin.controls.posts.edit', label: 'Edit Posts', description: 'Lets admins update captions, media metadata, and post state.' },
  { key: 'admin.controls.posts.delete', label: 'Delete Posts', description: 'Lets admins permanently remove posts from the platform.' },
  { key: 'admin.controls.posts.feature', label: 'Feature Posts', description: 'Lets admins boost, feature, or pin important content.' },
  { key: 'admin.controls.posts.hide', label: 'Hide Posts', description: 'Lets admins suppress visibility without hard deletion.' },
  { key: 'admin.controls.posts.commentModeration', label: 'Moderate Comments', description: 'Lets admins review, flag, and remove post comments.' },
  { key: 'admin.controls.app.fullAccess', label: 'Full App Access', description: 'Marks the admin surface as having full operational control across app sections.' },
]

export const adminAppControls = [
  { key: 'admin.access.users', label: 'Users', description: 'Admin can manage user lifecycle, account state, and verification.' },
  { key: 'admin.access.content', label: 'Content', description: 'Admin can manage posts, stories, reels, comments, and moderation.' },
  { key: 'admin.access.marketplace', label: 'Marketplace', description: 'Admin can create, edit, and remove marketplace inventory.' },
  { key: 'admin.access.jobs', label: 'Jobs', description: 'Admin can manage job listings and recruiter-side flows.' },
  { key: 'admin.access.events', label: 'Events', description: 'Admin can control event publishing, updates, and deletion.' },
  { key: 'admin.access.communities', label: 'Communities', description: 'Admin can manage communities, groups, and their operations.' },
  { key: 'admin.access.pages', label: 'Pages', description: 'Admin can control public pages and page metadata.' },
  { key: 'admin.access.liveStreams', label: 'Live Streams', description: 'Admin can manage live sessions and moderation controls.' },
  { key: 'admin.access.notifications', label: 'Notifications', description: 'Admin can control campaigns, devices, and delivery operations.' },
  { key: 'admin.access.support', label: 'Support', description: 'Admin can work tickets, support queues, and escalations.' },
  { key: 'admin.access.settings', label: 'Settings', description: 'Admin can change platform settings and visibility behavior.' },
]
